export { INPUT_KEY_BACKSPACE } from './key';

export {
  SIZE_EXTRA_SMALL,
  SIZE_LARGE,
  SIZE_MEDIUM,
  SIZE_SMALL,
  DEFAULT_BACKGROUND_COLOR_OPACITY,
  DEFAULT_BORDER_COLOR,
  DEFAULT_ERROR_BACKGROUND_COLOR,
  DEFAULT_ERROR_BORDER_COLOR,
  DEFAULT_FOCUS_BACKGROUND_COLOR,
  DEFAULT_FOCUS_BORDER_COLOR,
  DEFAULT_VALID_BACKGROUND_COLOR,
  DEFAULT_VALID_BORDER_COLOR
} from './styles';